"""initial schema

Revision ID: 59b6941e44fd
Revises: 
Create Date: 2026-04-21 06:23:35.781268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b6941e44fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carreras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre_norm', sa.Text(), nullable=False),
    sa.Column('nombre_variantes', sa.Text(), nullable=True),
    sa.Column('area_conocimiento', sa.String(length=100), nullable=True),
    sa.Column('nivel', sa.String(length=30), nullable=True),
    sa.Column('duracion_anios', sa.SmallInteger(), nullable=True),
    sa.Column('onet_codes_relacionados', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_norm')
    )
    op.create_table('ies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clave_sep', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('nombre_corto', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('subsistema', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('matricula_total', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave_sep')
    )
    op.create_table('kpi_historico',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=20), nullable=True),
    sa.Column('entidad_id', sa.String(length=36), nullable=True),
    sa.Column('entidad_nombre', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('kpi_nombre', sa.String(length=30), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('metadatos', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kpi_historico', 'kpi_historico', ['entidad_tipo', 'entidad_id', 'kpi_nombre', 'fecha'], unique=False)
    op.create_table('noticias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('fuente', sa.String(length=50), nullable=True),
    sa.Column('fecha_pub', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_ingesta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('tipo_impacto', sa.String(length=30), nullable=True),
    sa.Column('n_empleados', sa.Integer(), nullable=True),
    sa.Column('empresa', sa.Text(), nullable=True),
    sa.Column('causa_ia', sa.Text(), nullable=True),
    sa.Column('resumen_claude', sa.Text(), nullable=True),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('ocupaciones',
    sa.Column('onet_code', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('p_automatizacion', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('p_augmentacion', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('tareas', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('salario_mediana_usd', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('onet_code')
    )
    op.create_table('vacantes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('empresa', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('salario_min', sa.Integer(), nullable=True),
    sa.Column('salario_max', sa.Integer(), nullable=True),
    sa.Column('fecha_pub', sa.Date(), nullable=True),
    sa.Column('fuente', sa.String(length=30), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('nivel_educativo', sa.String(length=50), nullable=True),
    sa.Column('experiencia_anios', sa.SmallInteger(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ies_id', sa.String(length=36), nullable=True),
    sa.Column('carrera_id', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('severidad', sa.String(length=10), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('accion_sugerida', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.ForeignKeyConstraint(['ies_id'], ['ies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrera_ies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('carrera_id', sa.String(length=36), nullable=True),
    sa.Column('ies_id', sa.String(length=36), nullable=True),
    sa.Column('ciclo', sa.String(length=10), nullable=True),
    sa.Column('matricula', sa.Integer(), nullable=True),
    sa.Column('egresados', sa.Integer(), nullable=True),
    sa.Column('costo_anual_mxn', sa.Integer(), nullable=True),
    sa.Column('plan_estudio_skills', sa.Text(), nullable=True),
    sa.Column('ultima_actualizacion_plan', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.ForeignKeyConstraint(['ies_id'], ['ies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrera_id', 'ies_id', 'ciclo')
    )
    op.create_table('escenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ies_id', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('horizonte_anios', sa.SmallInteger(), nullable=True),
    sa.Column('acciones', sa.Text(), nullable=True),
    sa.Column('proyecciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ies_id'], ['ies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('escenarios')
    op.drop_table('carrera_ies')
    op.drop_table('alertas')
    op.drop_table('vacantes')
    op.drop_table('ocupaciones')
    op.drop_table('noticias')
    op.drop_index('idx_kpi_historico', table_name='kpi_historico')
    op.drop_table('kpi_historico')
    op.drop_table('ies')
    op.drop_table('carreras')
    # ### end Alembic commands ###
